# Generated by Django 4.2.2 on 2023-07-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networksLearning', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Helpers',
        ),
    ]
